name: CI
on: [push]

jobs:
  build:
    name: Build Job
    runs-on: macos-latest
    defaults:
      run:
        working-directory: Source

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history for GitVersion
        run: git fetch --prune --unshallow

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.2
        with:
          versionSpec: '5.2.x'

      # Use the id to reference the GitVersion values in future steps.
      - name: GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.2

      - run: |
          echo PNuGetVersionV2: ${{ steps.gitversion.outputs.nuGetVersion }}

      - name: NuGet
        run: nuget restore

      - name: Build
        run: msbuild /t:Rebuild /p:Configuration=Debug /p:Platform=iPhoneSimulator