name: CI
on: [push]

jobs:
  build:
    name: Build Job
    runs-on: macos-latest
    defaults:
      run:
        working-directory: Source

    steps:
      - uses: actions/checkout@v2

      - name: NuGet
        run: nuget restore

      - name: Build
        run: msbuild /t:Rebuild /p:Configuration=Debug /p:Platform=iPhoneSimulator