name: CI
on: [push]

jobs:
  build:
    name: Build Job
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Change to Source Directory
        run: cd Source

      - name: NuGet
        run: dotnet restore

      - name: Build
        run: msbuild /t:Rebuild /p:Configuration=Debug /p:Platform=iPhoneSimulator